LIB_TARGET=$(OUT_DIR)/libWiflyControl.a
LIB_SRC=$(wildcard $(LIB_DIR)/*.cpp)
LIB_INC=-I$(FW_DIR)
LIB_OBJ=$(LIB_SRC:%.cpp=%.o)

%.o: %.cpp
	$(GPP) $(CFLAGS) $(LIB_INC) -c $< -o $@

outdir:
	mkdir -p ${OUT_DIR}

library: outdir $(LIB_OBJ)
	echo $(LIB_OBJ)
	rm -f $(LIB_TARGET)	
	ar cq $(LIB_TARGET) $(LIB_OBJ)

library_clean:
	echo "cleaning library"
	echo $(LIB_SRC) 
	echo $(LIB_OBJ)
	echo $(LIB_INC)
	rm -f $(LIB_DIR)/*.o
	rm -f $(LIB_TARGET)

